spring:
  application:
    name: PRODUTOS-SERVICE
  datasource:
    url: jdbc:h2:mem:produtosdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8100 # Primeira porta da faixa 8100-8199

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/